
namespace den0bot
{
    public static class Config
    {
        public static readonly string telegam_token = REPLACE_ME;
        public static readonly string osu_token = REPLACE_ME;
        public static readonly string youtube_token = REPLACE_ME;

        public static readonly string[] memes =
        {
            "http://i.imgur.com/qfXXsZD.jpg",
            "http://i.imgur.com/MJHZuPW.jpg",
            "http://i.imgur.com/krQ6Rov.jpg",
            "http://i.imgur.com/Fb9gRmu.jpg",
            "http://i.imgur.com/FyrNkU5.jpg",
            "http://i.imgur.com/LrepqSw.jpg",
            "http://i.imgur.com/grjgj0F.jpg",
            "http://i.imgur.com/AA5OE0Z.jpg",
            "http://i.imgur.com/lApHXRg.jpg",
            "http://i.imgur.com/9opPXJR.jpg",
            "http://i.imgur.com/huUmd8E.jpg",
            "http://i.imgur.com/H18fTAy.png",
            "http://i.imgur.com/gxiQout.jpg",
            "http://i.imgur.com/smRNA9B.jpg",
            "http://i.imgur.com/WEspDsf.jpg",
            "http://i.imgur.com/8BK5cYT.png",
            "http://i.imgur.com/WIQ5X2Wg.jpg",
            "http://i.imgur.com/vMipKsi.jpg",
            "http://i.imgur.com/WUIhiTw.png",
            "http://i.imgur.com/BjDYVJU.jpg",
            "http://i.imgur.com/pl7kg3D.jpg",
            "http://i.imgur.com/3QCiyAe.jpg",
            "http://i.imgur.com/mUJ5tc6.jpg",
            "http://i.imgur.com/KmyzA5z.jpg",
            "http://i.imgur.com/a7ntMf0.jpg",
            "http://i.imgur.com/R66dZFH.jpg",
            "http://i.imgur.com/EfQShTf.jpg",
            "http://i.imgur.com/FQeqkuf.png",
            "http://i.imgur.com/sONRvCs.jpg",
            "http://i.imgur.com/C06kk20.jpg",
            "http://i.imgur.com/mOWrC9y.jpg",
            "http://i.imgur.com/SJJK9OK.png",
            "http://i.imgur.com/Lq0Cl4A.jpg",
            "http://i.imgur.com/ShmbT4Y.jpg",
            "http://i.imgur.com/u551pJn.png",
            "http://i.imgur.com/T8b3rDA.png",
            "http://i.imgur.com/yxxK0y7.jpg",
            "http://i.imgur.com/9XGVPHT.jpg",
            "http://i.imgur.com/ruHPzfR.png",
            "http://i.imgur.com/AfzF4h8.jpg",
            "http://i.imgur.com/PiygO7m.png",
            "http://i.imgur.com/b2iNiuh.png",
            "http://i.imgur.com/GxZh1Gc.jpg",
            "http://i.imgur.com/fABtP0X.jpg",
            "http://i.imgur.com/y3Jh0T4.jpg",
            "http://i.imgur.com/L9CG7wT.jpg",
            "http://i.imgur.com/dO71O6u.png",
            "http://i.imgur.com/B7eWzkC.jpg",
            "http://i.imgur.com/bBOvveN.jpg",
            "http://i.imgur.com/ebEYrpX.jpg",
            "http://i.imgur.com/6llmK9T.jpg",
            "http://i.imgur.com/kUgFQQG.jpg",
            "http://i.imgur.com/B8Du6jh.jpg",
            "http://i.imgur.com/Xq3V3PG.png",
            "http://i.imgur.com/bNT62YH.jpg",
            "http://i.imgur.com/DdaCEOs.jpg",
            "http://i.imgur.com/yQiJbXG.jpg",
            "http://i.imgur.com/Dahu8ac.jpg",
            "http://i.imgur.com/NYK3n82.jpg",
            "http://i.imgur.com/zgxdPq3.jpg",
            "http://i.imgur.com/1cus06p.jpg",
            "http://i.imgur.com/XAgF3XL.jpg",
            "http://i.imgur.com/OrGsCSt.jpg",
            "http://i.imgur.com/dzHcxGY.jpg",
            "http://i.imgur.com/VE4y3rM.jpg",
            "http://i.imgur.com/Qot2k5t.png",
            "http://i.imgur.com/jDgMb2K.png",
            "http://i.imgur.com/r9ZSIF4.png"
        };
    }
}
